apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfedorov-my-go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfedorov-my-go-server
  template:
    metadata:
      labels:
        app: sfedorov-my-go-server
    spec:
      containers:
      - name: sfedorov-my-go-server
        image: sfedorov-my-go-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"